import './globals.css';
import type { Metadata } from 'next';

import clsx from 'clsx';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx('font-sans antialiased')}>{children}</body>
    </html>
  );
}
